{
 "title": "Triggers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Product expiration triggers average misfire duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quartz_trigger_productexpiration_misfire_average_time_miliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product expiration average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "app_product_afterexpiration_average_time_miliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product expiration triggers count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quartz_trigger_productexpiration_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "quartz_trigger_productexpiration_misfire_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of products after expiration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "app_product_afterexpiration_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}